'use client';

// Major Government Projects & Spending section
// Data from propertyData.government

import { usePropertyData } from '@/lib/PropertyDataContext';

export default function GovernmentSection() {
  const propertyData = usePropertyData();
  const { government } = propertyData;

  return (
    <section id="government" style={{ marginBottom: '64px' }}>
      <h2 style={{ fontSize: '1.75rem', fontWeight: 700, color: '#1a2b3c', margin: '0 0 24px 0' }}>
        Major Government Projects &amp; Spending
      </h2>

      {government.projects.length > 0 ? (
        <>
          {government.regionName && (
            <p style={{ color: '#374151', fontSize: '0.95rem', lineHeight: 1.7, marginBottom: '12px' }}>
              Below are the major government projects and infrastructure spending in {government.regionName}:
            </p>
          )}
          <p style={{ color: '#9CA3AF', fontSize: '0.78rem', marginBottom: '32px', fontStyle: 'italic' }}>
            Content in this section was researched and generated by AI (Claude, Anthropic). Figures are indicative and sourced from publicly available government announcements and media reports. Not provided by Christian Baumann.
          </p>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '32px' }}>
            {government.projects.map((project, i) => (
              <div key={i}>
                <h3
                  style={{
                    fontSize: '1.05rem',
                    fontWeight: 700,
                    color: '#1a2b3c',
                    marginBottom: '10px',
                  }}
                >
                  {project.title}
                </h3>
                <p style={{ color: '#374151', fontSize: '0.92rem', lineHeight: 1.7, marginBottom: '12px' }}>
                  {project.description}
                </p>
                <ul style={{ listStyle: 'none', padding: 0, margin: 0, display: 'flex', flexDirection: 'column', gap: '7px' }}>
                  {project.bullets.map((bullet, j) => (
                    <li key={j} style={{ display: 'flex', alignItems: 'baseline', gap: '10px', fontSize: '0.9rem', color: '#374151' }}>
                      <span style={{ color: '#9CA3AF', fontSize: '0.6rem', flexShrink: 0 }}>●</span>
                      <span>{bullet}</span>
                    </li>
                  ))}
                </ul>
                {project.sourceUrl && (
                  <a
                    href={project.sourceUrl}
                    target="_blank"
                    rel="noopener noreferrer"
                    style={{ display: 'inline-block', marginTop: '8px', fontSize: '0.75rem', color: '#6B7280', textDecoration: 'underline' }}
                  >
                    Source ↗
                  </a>
                )}
              </div>
            ))}
          </div>
        </>
      ) : (
        <p style={{ color: '#9CA3AF', fontSize: '0.875rem', fontStyle: 'italic' }}>
          Government project data will appear here once populated.
        </p>
      )}
    </section>
  );
}
