'use client';

// Sales & Rent Comparisons section — two side-by-side tables

import { usePropertyData } from '@/lib/PropertyDataContext';

const TABLE_HEADER_STYLE: React.CSSProperties = {
  backgroundColor: '#4a5568',
  color: '#FFFFFF',
  padding: '10px 14px',
  textAlign: 'left',
  fontSize: '0.82rem',
  fontWeight: 600,
  letterSpacing: '0.02em',
};

const TABLE_CELL_STYLE: React.CSSProperties = {
  padding: '10px 14px',
  fontSize: '0.875rem',
  color: '#374151',
  borderBottom: '1px solid #F3F4F6',
};

export default function SalesComparisonsSection() {
  const propertyData = usePropertyData();
  const { salesComparisons } = propertyData;
  const { salesTable, rentTable } = salesComparisons;

  const hasData = salesTable.rows.length > 0 || rentTable.rows.length > 0;

  return (
    <section id="sales-comparisons" style={{ marginBottom: '64px' }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '8px', flexWrap: 'wrap' }}>
        <h2 style={{ fontSize: '1.75rem', fontWeight: 700, color: '#1a2b3c', margin: 0 }}>
          Market Comparables
        </h2>
        <span style={{
          display: 'inline-flex', alignItems: 'center',
          backgroundColor: '#FEF3C7', color: '#92400E',
          fontSize: '0.7rem', fontWeight: 700, letterSpacing: '0.05em',
          padding: '2px 8px', borderRadius: '4px', border: '1px solid #F59E0B',
        }}>
          AI
        </span>
      </div>
      <p style={{ color: '#9CA3AF', fontSize: '0.78rem', marginBottom: '24px', fontStyle: 'italic' }}>
        Comparable sales and rental data researched and generated by AI (Claude, Anthropic) from publicly available market data. Not provided by Christian Baumann.
      </p>

      {hasData ? (
        <>
          <div style={{ display: 'flex', gap: '24px', flexWrap: 'wrap', marginBottom: '24px' }}>
            {salesTable.rows.length > 0 && (
              <div style={{ flex: '1 1 280px', border: '1px solid #E5E7EB', borderRadius: '8px', overflow: 'hidden' }}>
                <table style={{ width: '100%', borderCollapse: 'collapse' }}>
                  <thead>
                    <tr>
                      {salesTable.headers.map((h) => (
                        <th key={h} style={TABLE_HEADER_STYLE}>{h}</th>
                      ))}
                    </tr>
                  </thead>
                  <tbody>
                    {salesTable.rows.map((row, i) => (
                      <tr
                        key={i}
                        style={{ backgroundColor: '#FFFFFF' }}
                        onMouseEnter={(e) => { (e.currentTarget as HTMLTableRowElement).style.backgroundColor = '#F9FAFB'; }}
                        onMouseLeave={(e) => { (e.currentTarget as HTMLTableRowElement).style.backgroundColor = '#FFFFFF'; }}
                      >
                        {row.map((cell, j) => (
                          <td key={j} style={TABLE_CELL_STYLE}>{cell}</td>
                        ))}
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}

            {rentTable.rows.length > 0 && (
              <div style={{ flex: '2 1 380px', border: '1px solid #E5E7EB', borderRadius: '8px', overflow: 'hidden' }}>
                <table style={{ width: '100%', borderCollapse: 'collapse' }}>
                  <thead>
                    <tr>
                      {rentTable.headers.map((h) => (
                        <th key={h} style={TABLE_HEADER_STYLE}>{h}</th>
                      ))}
                    </tr>
                  </thead>
                  <tbody>
                    {rentTable.rows.map((row, i) => (
                      <tr
                        key={i}
                        style={{ backgroundColor: '#FFFFFF' }}
                        onMouseEnter={(e) => { (e.currentTarget as HTMLTableRowElement).style.backgroundColor = '#F9FAFB'; }}
                        onMouseLeave={(e) => { (e.currentTarget as HTMLTableRowElement).style.backgroundColor = '#FFFFFF'; }}
                      >
                        {row.map((cell, j) => (
                          <td key={j} style={TABLE_CELL_STYLE}>{cell}</td>
                        ))}
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </div>

          <p style={{ color: '#9CA3AF', fontSize: '0.8rem', marginBottom: '24px' }}>
            Source: REA Group / CoreLogic. Data is approximate and for reference only. All figures in AUD.
          </p>
        </>
      ) : (
        <p style={{ color: '#9CA3AF', fontSize: '0.875rem', fontStyle: 'italic' }}>
          Market comparable data will appear here once populated.
        </p>
      )}
    </section>
  );
}
